### ISSUE TITLE
can't install this with vagrant-vbguest plugin installed

### ISSUE THREAD

**Issue by BenoitLeveque** [Elao/symfony-standard#120]
I have the vagrant-vbguest plugin installed. This plugin update the vm GuestAdditions to keep it in sync with host version.

see the log : https://gist.github.com/BenoitLeveque/3213b29aa683a90dc6b4e2274472bba9

**Comment by nervo** [comment]
Oops, my bad: https://github.com/manala/packer-template-skeleton/commit/91ab154069e4632b65c1ad857d783db24b68b864

We will release a new box asap
