### ISSUE TITLE
Vendor name should allow empty string

### ISSUE THREAD

**Issue by BenoitLeveque** [Elao/symfony-standard#25]
```
Vendor name: 
 The name should only contains alphanumeric characters (and hyphen)
```

**Comment by nervo** [comment]
Empty string and/or alphanumeric ?

**Comment by benji07** [comment]
The vendor name should not be required

Envoyé de mon iPhone

**Comment by nervo** [comment]
It's not :)

**Comment by benji07** [comment]
But with the composer create-project command it is (it's a bug)

**Comment by nervo** [comment]
Oh, ok, sorry, i thought you were talking about Vagrantfile.
