### ISSUE TITLE
Should we delete .htaccess ?

### ISSUE THREAD

**Issue by nervo** [Elao/symfony-standard#30]

**Comment by benji07** [comment]
Sensiolabs Insight doesn't like them, and we don't use them. But for apache users we need to keep the one inside the web directory

**Comment by emerick42** [comment]
Is there any user of the Elao Symfony standard using Apache? I vote for deleting this file ! :fire:

**Comment by nervo** [comment]
Seems fair and legit

**Comment by gfaivre** [comment]
Considering Nginx as the default webserver choices (for many reasons) @elao, deleting it seems logical to me. However keep the default htaccess content in the "Readme" for Apache users could make sense.

**Comment by nervo** [comment]
I like it like that !
Let's remove all these htaccess, and write a notice in the readme.

**Comment by nervo** [comment]
Radically solved by @hyvs :)

https://github.com/Elao/symfony-standard/commit/9a756f595664a49a861cdf8479c95242b66cb955
