### ISSUE TITLE
Should we use PSR4 in composer.json ?

### ISSUE THREAD

**Issue by nervo** [Elao/symfony-standard#31]

**Comment by benji07** [comment]
:+1:

**Comment by Tom32i** [comment]
:+1:

**Comment by benji07** [comment]
yes but, we can't set a default value inside the composer.json ?

Or maybe the VendorName/ProjectName/ : src

**Comment by nervo** [comment]
We did it during the last symfony 2.7 syncro

https://github.com/Elao/symfony-standard/commit/bdfa77c51fe644d3037a9780f3964892b01796c4
