### ISSUE TITLE
Fails during installation

### ISSUE THREAD

**Issue by tristanbes** [Elao/symfony-standard#35]
When we're asked by the installer to choose (Y/n) if we want to modify those files:
```
Vagrantfile
..yml
...
```

Answering `Y` or `y` and then hitting enter gives this error:  
```
[InvalidArgumentException]                            
  Maximum number of attempts must be a positive value. 
```

Ubuntu 10.04

**Comment by maximecolin** [comment]
Unbutu ? Don't know this OS. Try with Ubuntu, it should work better ;)

**Comment by tristanbes** [comment]
Ca explique peut être pourquoi j'arrive jamais a le pronnoncer :D

**Comment by tristanbes** [comment]
It also happens on 10.10.3 on a fresh installation :)

**Comment by benji07** [comment]
Well, did you try to update your composer version (with composer self-update)

it work's for me
![capture d ecran 2015-05-20 a 17 07 36](https://cloud.githubusercontent.com/assets/166890/7729000/c19a6032-ff12-11e4-802c-9ef23bf89734.png)

**Comment by tristanbes** [comment]
It's a fresh install so I have the latest composer version 
It was working for me too before formatting.

```
Composer version 1.0-dev (bc45d9185513575434021527d7756420e9f4b2cf) 2015-05-11 14:49:39
You are already using composer version bc45d9185513575434021527d7756420e9f4b2cf
```

**Comment by tristanbes** [comment]
![2015-05-20_1722](https://cloud.githubusercontent.com/assets/346010/7729399/dc043df6-ff14-11e4-9c23-7515bf0a18de.png)

**Comment by benji07** [comment]
@tristanbes i just update composer, and it doesn't work anymore :(

**Comment by nervo** [comment]
Fix by https://github.com/Elao/symfony-standard/commit/62f4894e697a00c572b083e2147c14cdcb8b53e0

(damned composer doc...)
