### ISSUE TITLE
Run the provisionning as `ansible_local`

### ISSUE THREAD

**Issue by benji07** [Elao/symfony-standard#93]
As our roles are not compatible with ansible 2.0, we must be able to run the provisionning with `ansible_local` options in vagrant 1.8.

It work but i still have one bug, we can't have extra vars

```
ERROR: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Ansible failed to complete successfully. Any error output should be
```

To fix that I remove the extra vars from the Vagrantfile, and I added it inside the `ansible/group_vars/env_dev.yml` file

**Comment by maximecolin** [comment]
What about making our roles compatible with ansible 2.0 ? Why aren't they compatible ?

**Comment by benji07** [comment]
@hyvs and @nervo want to make our roles compatible, but right now you can't install the symfony standard because some roles are not compatible.

And running the provisionning inside the vm would allow us to not rely on the ansible install outside of the vm

**Comment by msheakoski** [comment]
@benji07 The "Expecting property name enclosed in double quotes" is related to a bug in Vagrant. It is not correctly quoting the variables before passing them to Ansible. You will see the error if you run `vagrant provision --debug`.

mitchellh/vagrant#6726
mitchellh/vagrant#6820

**Comment by nervo** [comment]
Should we automate the galaxy downloading of roles on every provisionning ?

See galaxy_role_file/galaxy_roles_path right there: https://www.vagrantup.com/docs/provisioning/ansible_common.html

Or maybe, we can hack vagrant parameters... Something like "vagrant provision --roles"
